logging:
  level:
    root: WARN
    az.baxtiyargil.cleanarch: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: cleanarch
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create